### ISSUE TITLE
**OLD BRIDGE INTERACTION** Stuck Transaction for user Aiz | BlockRaiders

### ISSUE THREAD

**Issue by dylie** [Ether1Project/stuck-bridge-transactions#1]
**James, this contract call was done over the OLD bridge.**

TX: https://explorer.ethoprotocol.com/tx/0x3ea6bfb6cc509cd25b1fd0852211c07dd736b2108edd7b743372b1c83b0b2c27/internal-transactions

AMOUNT STUCK: 

**3582.4 ETHO** 

RETURN ADDRESS:

**0x02E3f540bE055029cD072a46899e61eB0D8566E8**

_Stuck since September-10-2021 09:52:35 PM +1 UTC_

Confirmed by Dylie

**Comment by Dev-JamesR** [comment]
Wrapped ETHO has been minted:

https://etherscan.io/tx/0x0d7c121aced0fd35defac87d310aa8dcbfeaa87d749afa9194f4235b3229cbc5
