### ISSUE TITLE
**NEW BRIDGE TRANSACTION** Stuck transaction for user Joy

### ISSUE THREAD

**Issue by dylie** [Ether1Project/stuck-bridge-transactions#2]
**James, this contract call was done over the NEW bridge.**

TX: https://explorer.ethoprotocol.com/tx/0x7cb6ff4bc6ca2ac1bcb9469ea82c19212f78d2ab06fa54ea74b59be51697f7a9/internal-transactions

AMOUNT STUCK: 

**126550 ETHO** 

RETURN ADDRESS:

**0xdb81C64854501C956D6788127422Caa8Aa73d0d5**

_Stuck since December-04-2021 11:09:30 AM +1 UTC_

Confirmed by Dylie

**Comment by Dev-JamesR** [comment]
Wrapped ETHO has been minted:

https://etherscan.io/tx/0x8b5791ef63970f0484656cd6bf58551c557848ae26aa44f45bc7ae819a166bd4

**Comment by dylie** [comment]
User confirmed. 

Funds arrived
