### ISSUE TITLE
**NEW BRIDGE TRANSACTION** stuck transaction for user Benjamin | Culdz

### ISSUE THREAD

**Issue by dylie** [Ether1Project/stuck-bridge-transactions#3]
**James, this contract call was done over the NEW bridge.**

TX: 

https://explorer.ethoprotocol.com/tx/0x3a9b4a939f7f9d63c1d9891f45e0eb5f67dd3b8c97f1c14fb9471f58ec0c1e2a/internal-transactions

AMOUNT STUCK: 

**3179 ETHO** 

RETURN ADDRESS:

**0x35287A0Aa07D396BAE1192DB4b3ba4A5169b6aBe**

_Stuck since November-07-2021 02:50:21 PM +1 UTC_

Confirmed by Dylie

**Comment by dylie** [comment]
Hey @Dev-JamesR any ETA on this issue?

**Comment by Dev-JamesR** [comment]
Wrapped ETHO Minted on tx:

https://etherscan.io/tx/0x1f0cff9f8fdb6eadd11167d8393135441763c12bd5a020d09860fbcd7c85d99e

**Comment by dylie** [comment]
User confirmed.

Funds arrived
