### ISSUE TITLE
Bridge issue for user NOICE

### ISSUE THREAD

**Issue by Legacytrx** [Ether1Project/stuck-bridge-transactions#4]
BRdige direction: wETHO -> ETHO

TX:https://etherscan.io/tx/0x55d145d10ad655d3cd5761854844850fb70c3485ccf992ced506d22bd038b992

AMOUNT: 30,200.445 wETHO received from Kucoin10 wallet and burned on wETHO side

ETHO ADDRESS: https://explorer.ethoprotocol.com/address/0xA22bE7174f6DC2f955bE918294E052922cD236EC

**Comment by IedSupo** [comment]
Mainet ETHO has been collected:

https://explorer.ethoprotocol.com/tx/0xa049fd8fb590cab2b153005718173591548a1ecba60ea63fc950dd709960d183
